/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.xdpiqbx;

import com.xdpiqbx.db.services.DatabaseMigrateService;
import com.xdpiqbx.db.services.DatabaseQueryService;

public class App {
    public static void main(String[] args) {
        DatabaseMigrateService.migrateDatabase();
        DatabaseQueryService.printResult();
    }
}